module.exports = [
  { nombre: 'LANUS', provincia: 'BUENOS AIRES' },
  { nombre: 'LOMAS DE ZAMORA', provincia: 'BUENOS AIRES' },
  { nombre: 'LA PLATA', provincia: 'BUENOS AIRES' },
  { nombre: 'CAPITAL FEDERAL', provincia: 'BUENOS AIRES' },
  { nombre: 'QUILMES', provincia: 'BUENOS AIRES' },
  { nombre: 'FLORENCIO VARELA', provincia: 'BUENOS AIRES' },
  { nombre: 'MONTE GRANDE', provincia: 'BUENOS AIRES' },
  { nombre: 'BURZACO', provincia: 'BUENOS AIRES' },
  { nombre: 'BERAZATEGUI', provincia: 'BUENOS AIRES' },
  { nombre: 'LONGCHAMPS', provincia: 'BUENOS AIRES' },
  { nombre: 'TEMPERLEY', provincia: 'BUENOS AIRES' },
  { nombre: 'GLEW', provincia: 'BUENOS AIRES' },
  { nombre: 'GONZALEZ CATAN', provincia: 'BUENOS AIRES' },
  { nombre: 'GUERNICA', provincia: 'BUENOS AIRES' },
  { nombre: 'EZEIZA', provincia: 'BUENOS AIRES' },
  { nombre: 'LAFERERRE', provincia: 'BUENOS AIRES' },
  { nombre: 'ADROGUE', provincia: 'BUENOS AIRES' },
  { nombre: 'CLAYPOLE', provincia: 'BUENOS AIRES' },
  { nombre: 'BANFIELD', provincia: 'BUENOS AIRES' },
  { nombre: 'AVELLANEDA', provincia: 'BUENOS AIRES' },
  { nombre: 'MERLO', provincia: 'BUENOS AIRES' },
  { nombre: 'SAN JUSTO', provincia: 'BUENOS AIRES' },
  { nombre: 'RAFAEL CALZADA', provincia: 'BUENOS AIRES' },
  { nombre: 'LA MATANZA', provincia: 'BUENOS AIRES' },
  { nombre: 'MORON', provincia: 'BUENOS AIRES' },
  { nombre: 'VIRREY DEL PINO', provincia: 'BUENOS AIRES' },
  { nombre: 'ALEJANDRO KORN', provincia: 'BUENOS AIRES' },
  { nombre: 'LAVALLOL', provincia: 'BUENOS AIRES' },
  { nombre: 'SAN VICENTE', provincia: 'BUENOS AIRES' },
  { nombre: 'CAÑUELAS', provincia: 'BUENOS AIRES' },
  { nombre: 'SAN FRANCISCO SOLANO', provincia: 'BUENOS AIRES' },
  { nombre: 'MORENO', provincia: 'BUENOS AIRES' },
  { nombre: 'RAFAEL CASTILLO', provincia: 'BUENOS AIRES' },
  { nombre: 'ITUZAINGO', provincia: 'BUENOS AIRES' },
  { nombre: 'SAN MARTIN', provincia: 'BUENOS AIRES' },
  { nombre: 'WILDE', provincia: 'BUENOS AIRES' },
  { nombre: 'GENERAL BELGRANO', provincia: 'BUENOS AIRES' },
  { nombre: 'BERNAL', provincia: 'BUENOS AIRES' },
  { nombre: 'BRANDSEN', provincia: 'BUENOS AIRES' },
  { nombre: 'RAMOS MEJIA', provincia: 'BUENOS AIRES' },
  { nombre: 'HURLINGHAM', provincia: 'BUENOS AIRES' },
  { nombre: 'CASTELAR', provincia: 'BUENOS AIRES' },
  { nombre: 'ISIDRO CASANOVA', provincia: 'BUENOS AIRES' },
  { nombre: 'BERISSO', provincia: 'BUENOS AIRES' },
  { nombre: 'MAR DEL PLATA', provincia: 'BUENOS AIRES' },
  { nombre: 'SAN MIGUEL DEL MONTE', provincia: 'BUENOS AIRES' },
  { nombre: 'CASEROS', provincia: 'BUENOS AIRES' },
  { nombre: 'CIUDADELA', provincia: 'BUENOS AIRES' },
  { nombre: 'CIUDAD EVITA', provincia: 'BUENOS AIRES' },
  { nombre: 'HAEDO', provincia: 'BUENOS AIRES' },
  { nombre: 'ENSENADA', provincia: 'BUENOS AIRES' },
  { nombre: 'PILAR', provincia: 'BUENOS AIRES' },
  { nombre: 'EL PALOMAR', provincia: 'BUENOS AIRES' },
  { nombre: 'GENERAL RODRIGUEZ', provincia: 'BUENOS AIRES' },
  { nombre: 'LOBOS', provincia: 'BUENOS AIRES' },
  { nombre: 'DOMSELAAR', provincia: 'BUENOS AIRES' },
  { nombre: 'RANCHOS', provincia: 'BUENOS AIRES' },
  { nombre: 'SAN ANTONIO DE PADUA', provincia: 'BUENOS AIRES' },
  { nombre: 'JOSE C. PAZ', provincia: 'BUENOS AIRES' },
  { nombre: 'TIGRE', provincia: 'BUENOS AIRES' },
  { nombre: 'LUJAN', provincia: 'BUENOS AIRES' },
  { nombre: 'CHASCOMUS', provincia: 'BUENOS AIRES' },
  { nombre: 'SAN ISIDRO', provincia: 'BUENOS AIRES' },
  { nombre: 'EL JAGUEL', provincia: 'BUENOS AIRES' },
  { nombre: 'REMEDIOS DE ESCALADA', provincia: 'BUENOS AIRES' },
  { nombre: 'TRISTAN SUAREZ', provincia: 'BUENOS AIRES' },
  { nombre: 'TURDERA', provincia: 'BUENOS AIRES' },
  { nombre: 'MATADEROS', provincia: 'BUENOS AIRES' },
  { nombre: 'LUIS GUILLON', provincia: 'BUENOS AIRES' },
  { nombre: 'VICENTE LOPEZ', provincia: 'BUENOS AIRES' },
  { nombre: 'VILLA BALLESTER', provincia: 'BUENOS AIRES' },
  { nombre: 'EZPELETA', provincia: 'BUENOS AIRES' },
  { nombre: 'LOMAS DEL MIRADOR', provincia: 'BUENOS AIRES' },
  { nombre: 'VILLA LUGANO', provincia: 'BUENOS AIRES' },
  { nombre: 'VILLA MADERO', provincia: 'BUENOS AIRES' },
  { nombre: 'TAPIALES', provincia: 'BUENOS AIRES' },
  { nombre: 'VILLA DOMINICO', provincia: 'BUENOS AIRES' },
  { nombre: 'TANDIL', provincia: 'BUENOS AIRES' },
  { nombre: 'LA TABLADA', provincia: 'BUENOS AIRES' },
  { nombre: 'CARCARAÑA', provincia: 'SANTA FE' },
  { nombre: 'VILLA ELISA', provincia: 'BUENOS AIRES' },
  { nombre: 'SAN FERNANDO', provincia: 'BUENOS AIRES' },
  { nombre: 'ESCOBAR', provincia: 'BUENOS AIRES' },
  { nombre: 'HUDSON', provincia: 'BUENOS AIRES' },
  { nombre: 'RANELAGH', provincia: 'BUENOS AIRES' },
  { nombre: 'VILLA CELINA', provincia: 'BUENOS AIRES' },
  { nombre: 'SARANDI', provincia: 'BUENOS AIRES' },
  { nombre: 'CHACO', provincia: 'CHACO' },
  { nombre: 'NAVARRO', provincia: 'BUENOS AIRES' },
  { nombre: 'SALADILLO', provincia: 'BUENOS AIRES' },
  { nombre: '9 DE ABRIL', provincia: 'BUENOS AIRES' },
  { nombre: 'VILLA GESELL', provincia: 'BUENOS AIRES' },
  { nombre: 'DOLORES', provincia: 'BUENOS AIRES' },
  { nombre: 'LAS HERAS', provincia: 'BUENOS AIRES' },
  { nombre: 'MALVINAS ARGENTINAS', provincia: 'BUENOS AIRES' },
  { nombre: 'SAN CLEMENTE DEL TUYU', provincia: 'BUENOS AIRES' },
  { nombre: 'CITY BELL', provincia: 'BUENOS AIRES' },
  { nombre: 'ESTEBAN ECHEVERRIA', provincia: 'BUENOS AIRES' },
  { nombre: 'OLIVOS', provincia: 'BUENOS AIRES' },
  { nombre: 'OLMOS', provincia: 'BUENOS AIRES' },
  { nombre: 'PILA', provincia: 'BUENOS AIRES' },
  { nombre: 'RODOLFO ALSINA', provincia: 'BUENOS AIRES' },
  { nombre: 'LOMA HERMOSA', provincia: 'BUENOS AIRES' },
  { nombre: 'MERCEDES', provincia: 'BUENOS AIRES' },
  { nombre: 'PERGAMINO', provincia: 'BUENOS AIRES' },
  { nombre: 'CORDOBA', provincia: 'CORDOBA' },
  { nombre: 'MARCOS PAZ', provincia: 'BUENOS AIRES' },
  { nombre: 'OLAVARRIA', provincia: 'BUENOS AIRES' },
  { nombre: 'PASO DEL REY', provincia: 'BUENOS AIRES' },
  { nombre: 'SANTOS LUGARES', provincia: 'BUENOS AIRES' },
  { nombre: 'DON TORCUATO', provincia: 'BUENOS AIRES' },
  { nombre: 'ALDO BONZI', provincia: 'BUENOS AIRES' },
  { nombre: 'LAS FLORES', provincia: 'BUENOS AIRES' },
  { nombre: 'MARTINEZ', provincia: 'BUENOS AIRES' },
  { nombre: 'MUNRO', provincia: 'BUENOS AIRES' },
  { nombre: 'ROSARIO', provincia: 'SANTA FE' },
  { nombre: 'SAENZ PEÑA', provincia: 'BUENOS AIRES' },
  { nombre: 'SANTA TERESITA', provincia: 'BUENOS AIRES' },
  { nombre: 'BOULOGNE', provincia: 'BUENOS AIRES' },
  { nombre: 'JEPPENER', provincia: 'BUENOS AIRES' },
  { nombre: 'SALTO', provincia: 'BUENOS AIRES' },
  { nombre: 'TORTUGUITAS', provincia: 'BUENOS AIRES' },
  { nombre: 'AZUL', provincia: 'BUENOS AIRES' },
  { nombre: 'GUTIERREZ', provincia: 'BUENOS AIRES' },
  { nombre: 'JOSE MARMOL', provincia: 'BUENOS AIRES' },
  { nombre: 'MIRAMAR', provincia: 'BUENOS AIRES' },
  { nombre: 'NECOCHEA', provincia: 'BUENOS AIRES' },
  { nombre: 'GENERAL PACHECO', provincia: 'BUENOS AIRES' },
  { nombre: 'SALTA', provincia: 'SALTA' },
  { nombre: 'BALCARCE', provincia: 'BUENOS AIRES' },
  { nombre: 'GENERAL MADARIAGA', provincia: 'BUENOS AIRES' }
];
